[package]
name = "bevy_yarn_slinger_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_yarn_slinger = { path = "../crates/bevy_plugin" }
bevy_yarn_slinger_example_ui = { path = "../crates/example_ui" }
bevy_editor_pls = "0.4"
bevy_sprite3d = "=2.4.0"

[dependencies.bevy]
version = "0.10"
default-features = false
features = ["bevy_core_pipeline", "bevy_pbr", "bevy_render", "bevy_sprite", "bevy_winit", "filesystem_watcher", "png", "x11", "bevy_gltf", "tonemapping_luts"]
